### ISSUE TITLE
Where to find jar  1.3.0-247-sakuli-se-SNAPSHOT ?

### ISSUE THREAD

**Issue by fadjer** [ConSol/sakuli-examples#3]
Hi,

I'm trying to run the java-example project which uses sakuli-java-dsl in version 1.3.0-247-sakuli-se-SNAPSHOT, my maven is unable to find it, and it's not in maven public repository up to now.

Many Thanks.

**Comment by s1hofmann** [comment]
Hi @fadjer,

1.3.0-247-sakuli-se-SNAPSHOT should be hosted on our own Nexus, which is included in the POM.
I'll check tomorrow and keep you updated.

**Comment by fadjer** [comment]
Any update on that please ? Many Thanks

**Comment by s1hofmann** [comment]
Hi @fadjer,

I'm sorry, but I'm currently really short on time. I'll try to give you an update as soon as possible.

**Comment by xela07ax** [comment]
> Hi @fadjer,
> 
> I'm sorry, but I'm currently really short on time. I'll try to give you an update as soon as possible.

There is no way to debug sakuli.
I changed to version 1.2.0, but an error comes out

cannot resolve resource '/org/sakuli/common' from classpath!
     at org.sakuli.javaDSL.AbstractSakuliTest.resolveResource(AbstractSakuliTest.java:74)
.......

**Comment by s1hofmann** [comment]
Hi @xela07ax,

we no longer actively support Sakuli v1.x (see [the Sakuli V1 repo](https://github.com/consol/sakuli#attention-eol-of-sakuli-1))

The latest version of Sakuli is available at https://sakuli.io/. A full rewrite which aims to provide a smooth migration from v1.x.
